---
apiVersion: ros.io/v1
kind: BackupSchedule
metadata:
  name: example-backup-schedule
spec:
  interval: 1m
  prune:
    interval: 2m
    retain:
      hourly: 1
  check:
    interval: 2m
  plans:
  - type: pod
    labelSelector:
      matchLabels:
        app: test
    fieldSelector:
    - field: metadata.namespace
      operator: equals
      value: default
  repository:
    name: restic-rest-config 
    namespace: default
