---
backup_job_image: ghcr.io/jess-sol/restic-k8s/job:latest
cluster_name: minikube
worker_service_account_name: walle

snap_class_mappings:
- storage_class: csi-hostpath-sc
  snapshot_class: csi-hostpath-snapclass
